#!/usr/bin/env python

import os, shmobj

x = shmobj.SHMINT(44)
y = shmobj.SHMINT(55)
z = shmobj.SHMINT(66)

l = shmobj.SHMLST([x,y,z])

# n = shmobj.SHMINT(99)
# l[1] = n
# print l

rc = os.fork()
if rc == 0:  # child
    n = shmobj.SHMINT(99)
    l[1] = n
else:
    (pid,stat) = os.waitpid(rc,0)
    print os.getpid(), l
