#!/usr/bin/env python

import os, shmobj

x = shmobj.SHMINT(44)
y = shmobj.SHMINT(55)
z = shmobj.SHMINT(66)
l = shmobj.SHMLST([x,y,z])
sem = shmobj.semaphore()
print l

sem.wait()
rc = os.fork()
if rc == 0:  # child
    sem.wait()
    print os.getpid(), l
else:
    n = shmobj.SHMINT(99)
    l[1] = n
    print os.getpid(), l
    sem.post()
    (pid,stat) = os.waitpid(rc,0)
