#!/usr/bin/env python

import os, shmobj

p = shmobj.SHMPTR(0)

rc = os.fork()
if rc == 0:
    x = shmobj.SHMINT(44)
    p.set(x.get_ptr())
else:
    (pid,stat) = os.waitpid(rc,0)
    a = p.get()
    y = shmobj.SHMINT(a,internal=True)  # note the 'internal'
    print "Y=", y
